### ISSUE TITLE
Sub-generators (component, mixin) run `all` generator

### ISSUE THREAD

**Issue by necolas** [flightjs/generator-flight#28]
If you try to run `yo flight:component` then it will actually invoke `yo flight:all`. @passy, have you guys made any changes to `yo` that could have introduced this bug? This generator hasn't changed for a while and used to work. Any idea how to fix this?

**Comment by passy** [comment]
@necolas Can't think of a change that could be the cause for that. It's probably something in the `generator` internals.

/cc'ing @SBoudrias @addyosmani for ideas.

**Comment by SBoudrias** [comment]
Hum, last `yo` versions have been release for about a week and this is the first I heard of this. (Generator-BBB use very similar style as yours and haven't broke)

I'll investigate this more deeply as soon as possible.

You're using `yo@1.1.2` and haven't the same issue when using an older version?

**Comment by SBoudrias** [comment]
Hey, I've run tests with `generator-flight` and multiple version of `yo@>=1.0` and haven't been able to reproduce.

A potential issue is if you mistyped a generator name like `yo flight:mixn foo`. That would've run the `flight:app` generator.

Still, if you can give me a particular version I can check it more in depth.

**Comment by necolas** [comment]
I'm running `yo` 1.1.2 and `generator-flight` 0.6.0. I haven't used this generator for a while so I'm not sure when the issue started.

Here's a screenshot of `yo flight:all name` running the main generator when invoking `flight:component`. Same thing happens if you try to run that sub-generator manually.

![](http://i.imgur.com/0Yz2G7T.png)

Is there anything else at the system level that could be interfering?

**Comment by SBoudrias** [comment]
Ok, I've only run it on Windows yet. I'll give it a try tonight on my mac.

It feels like these lines are wrong: `invoke   flight:component:E:\test\temp\node_modules\generatorflight\lib\generators\all\index.js`
