### ISSUE TITLE
Include a Gruntfile

### ISSUE THREAD

**Issue by SBoudrias** [flightjs/generator-flight#38]
I think it'd be good to include a Gruntfile.

It could handle the basic task like RJS minification you'll end up writing anyway.

Also, it'd be nice to have a server you can launch straight up so the app can run as soon as it is generated. Right now you must setup a server. (Ok, I just ran python simple http server, but it is not really great and don't support SVG)

**Comment by necolas** [comment]
Not using grunt. There is a gulpfile included.
