### ISSUE TITLE
Try to not repeat Requirejs config in tests

### ISSUE THREAD

**Issue by SBoudrias** [flightjs/generator-flight#39]
ATM the require.js config is repeat in the tests and in the app.

In [Backbone boilerplate](https://github.com/backbone-boilerplate/backbone-boilerplate) we reuse the same config and run tests with Karma too.

**Comment by necolas** [comment]
Where's the example of that? Looks like there is config going on in here: https://github.com/backbone-boilerplate/backbone-boilerplate/blob/master/test/runner.js

**Comment by necolas** [comment]
closing due to lack of follow up
