### ISSUE TITLE
Add ability to change generator install directory

### ISSUE THREAD

**Issue by jklegseth** [flightjs/generator-flight#41]
Currently all the generators install to hard-coded locations, i.e., the component generator does this:

```
 this.template('component.js', 'app/js/component/' + this.name + '.js');
 this.template('spec.js', 'test/spec/component/' + this.name + '.spec.js',
```

It would be useful to allow a second parameter to the generator to choose another folder:

```
yo flight:component my_amazing_component component/ui
```

My thinking is it would be okay to force the parent paths to `app/js` and `test/spec` but to then allow a subfolder path, so the above would result in:

```
app/js/component/ui/my_amazing_component.js'
test/spec/component/ui/my_amazing_component.spec.js'
```

In larger apps it quickly becomes cumbersome to dump all created components into a single folder. It's easy enough to generate and move them, but a look at various implementations suggests few are following the fixed generator locations (I'm not assuming they use the generators, just that this feature would facilitate real-world use):
- the [FlightJS sample app](https://github.com/flightjs/example-app) uses `js/component_data` and `js/component_ui`
- [Flight todomvc](https://github.com/tastejs/todomvc/tree/gh-pages/dependency-examples/flight) uses `js/data` and `js/ui`.
- [Tom Hamshere's book](http://www.packtpub.com/getting-started-with-twitter-flight/book) dumps ui, data and mixins all into `js/component`.
- [Tweetdeck](https://tweetdeck.twitter.com/) looks like it uses `ui`, `data` and `util`, and probably others

**Comment by necolas** [comment]
iirc yeoman has recently changed their api to make this possible via config files. haven't gotten around to migrating yet though because last time i looked the docs hadn't been updated.

**Comment by jklegseth** [comment]
Great, thanks, I'll keep an eye out. I figured it might be something they'd have in their API but didn't see it in the docs.
