### ISSUE TITLE
Peer Invalid - Fix is already on master

### ISSUE THREAD

**Issue by pierceray** [flightjs/generator-flight#43]
I was trying to use the generator-flight 0.7.2 tonight and kept coming across this error when invoking it:

```
npm ERR! peerinvalid The package karma-requirejs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma@0.10.10 wants karma-requirejs@~0.2.0

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "git://github.com/flightjs/generator-flight.git"
npm ERR! cwd /source/flight-app
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.10
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /source/flight-app/npm-debug.log
npm ERR! not ok code 0
```

I started poking around and saw that there is already a fix for this on master that was merged in March, but it was just never released it seems.  The 0.7.2 tag doesn't contain the changes at least.

I installed the master branch of the generator-flight and everything seems to install as expected now.

So just wondering if we could get a point release for the fixes that are already on master?

**Comment by necolas** [comment]
just published 0.7.3 to npm. should do the trick.
