### ISSUE TITLE
NPM error: karma-requirejs does not satisfy its siblings' peerDependencies

### ISSUE THREAD

**Issue by msecret** [flightjs/generator-flight#44]
I'm getting the following error when running yo flight <package>

npm ERR! peerinvalid The package karma-requirejs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma@0.10.10 wants karma-requirejs@~0.2.0

npm ERR! System Linux 3.8.0-41-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/msecret/Development/flight-yql
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/msecret/Development/flight-yql/npm-debug.log
npm ERR! not ok code 0

I've fixed by changing version of karam-requirejs to 0.2.0 in package.json such as follows:

"karma-requirejs": "~0.2.0",

**Comment by necolas** [comment]
Should be fixed in 0.7.3
