### ISSUE TITLE
Replace defaultAttrs with attributes for component template

### ISSUE THREAD

**Issue by ventaur** [flightjs/generator-flight#46]
Per the note here:
https://github.com/flightjs/flight/blob/master/doc/base_api.md#thisattributesobject

Is there a reason to keep the old defaultAttrs call in the template for backward compatibility? If not, I'll submit a pull request with the change.

**Comment by ventaur** [comment]
I get the feeling this is a version issue. Perhaps this is a premature issue then?

**Comment by necolas** [comment]
Published 0.8.0 which should fix this.
