### ISSUE TITLE
`npm run server` dies after serving one request

### ISSUE THREAD

**Issue by benshine** [flightjs/generator-flight#51]
I ran the generator in a clean directory then `npm run server`. I hit http://127.0.0.1:8080 in a browser. The server serves the page as expected but then the server dies hard:

┌─(~/workspace/flight-app-demo-2)───>npm run server                                                                                                  

> behave-please@0.0.0 server /Users/ben/workspace/flight-app-demo-2
> static app

serving "app" at http://127.0.0.1:8080

fs.js:1475
      throw new Error('start must be <= end');
            ^
Error: start must be <= end
    at new ReadStream (fs.js:1475:13)
    at Object.fs.createReadStream (fs.js:1436:10)
    at streamFile (/Users/ben/workspace/flight-app-demo-2/node_modules/node-static/lib/node-static.js:360:16)
    at Server.stream (/Users/ben/workspace/flight-app-demo-2/node_modules/node-static/lib/node-static.js:382:7)
    at Server.respondNoGzip (/Users/ben/workspace/flight-app-demo-2/node_modules/node-static/lib/node-static.js:332:14)
    at Server.respond (/Users/ben/workspace/flight-app-demo-2/node_modules/node-static/lib/node-static.js:347:14)
    at /Users/ben/workspace/flight-app-demo-2/node_modules/node-static/lib/node-static.js:144:22
    at Object.oncomplete (fs.js:107:15)

npm ERR! behave-please@0.0.0 server: `static app`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the behave-please@0.0.0 server script.
npm ERR! This is most likely a problem with the behave-please package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     static app
npm ERR! You can get their info via:
npm ERR!     npm owner ls behave-please
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.3.0
npm ERR! command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! cwd /Users/ben/workspace/flight-app-demo-2
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ben/workspace/flight-app-demo-2/npm-debug.log
npm ERR! not ok code 0

npm-debug.log: 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.10.24/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'server' ]
2 info using npm@1.3.21
3 info using node@v0.10.24
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info preserver behave-please@0.0.0
6 info server behave-please@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info behave-please@0.0.0 Failed to exec server script
9 error behave-please@0.0.0 server: `static app`
9 error Exit status 8
10 error Failed at the behave-please@0.0.0 server script.
10 error This is most likely a problem with the behave-please package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     static app
10 error You can get their info via:
10 error     npm owner ls behave-please
10 error There is likely additional logging output above.
11 error System Darwin 13.3.0
12 error command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "run" "server"
13 error cwd /Users/ben/workspace/flight-app-demo-2
14 error node -v v0.10.24
15 error npm -v 1.3.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

Reproduced a bunch of times.

**Comment by leeavital** [comment]
This happens to me as well:

npm --version # 1.4.23
node --version # 0.10.31
yo --version # 1.2.1

**Comment by benshine** [comment]
I ran this exact generator last week, on the same machine, and that app still runs as expected; the server stays alive for multiple requests -- so this is a new issue.

**Comment by benshine** [comment]
This seems to be intermittent. The server will stay up for one to dozens of requests, and then die.

**Comment by benshine** [comment]
I suspect this is caused by the underlying node-static server, and really nothing to do with flight-generator. Closing.

**Comment by kulte** [comment]
Well actually @benshine its sort of a generator-flight issue since it allows for a bad version of the dependency. I'd probably hardcode the dependency to a working version as mentioned in this issue https://github.com/cloudhead/node-static/issues/131. I'm going to make a pull request now.

**Comment by IonicaBizau** [comment]
Fixed via #134. See the pull request.
